apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dt7qz0weh-nodejs 
  janus-idp.io/tekton: dt7qz0weh-nodejs
  backstage.io/kubernetes-id: dt7qz0weh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dt7qz0weh-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml