apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dt7qz0weh-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dt7qz0weh-nodejs 
  name: dt7qz0weh-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dt7qz0weh-nodejs 
